ALTER TABLE ingestion.connector_query
    ADD COLUMN board_id bigint REFERENCES ingestion.public_job_board(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX connector_query_board_idx
    ON ingestion.connector_query(board_id) WHERE board_id IS NOT NULL;

-- A direct ATS board is one complete snapshot. It is not generated by a member search.
INSERT INTO ingestion.connector_query(public_id, source_id, board_id, query_signature, enabled)
SELECT gen_random_uuid(), board.source_id, board.id,
       lpad(md5('board|' || source.source_key || '|' || board.board_key), 64, '0'), false
FROM ingestion.public_job_board board
JOIN jobs.source source ON source.id = board.source_id
ON CONFLICT (source_id, query_signature) DO NOTHING;
